---
  - name: Set timezone to Europe/Moscow
    timezone:
      name: Europe/Moscow

  - name: make sure chronyd is installed
    yum:
      name: chrony
      state: latest
      update_cache: yes

  - name: Restart chronyd
    service:
      name: chronyd
      state: restarted

  - name: update hostname
    hostname:
      name: vm1-freeipa.test.local

  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items:
      - vm1-freeipa.test.local

  - name: Install firewalld
    yum:
      name: firewalld
      state: latest

  - name: start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes
    become: yes

  - name: open ports
    firewalld: port={{ item }} permanent=true state=enabled
    with_items:
      - 53/tcp
      - 53/udp
      - 80/tcp
      - 443/tcp
      - 88/tcp
      - 88/udp
      - 464/tcp
      - 464/udp
      - 123/udp
      - 389/tcp
      - 636/tcp

  - name: restart firewalld
    service:
      name: firewalld
      state: restarted
    become: yes

  - name: Disabling SELinux state
    selinux:
      state: disabled

  - name: install freeipa
    yum:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - ipa-server
      - ipa-server-dns

  - name: Update nss* for fix "ERROR CA did not start in 300.0s"
    yum:
      name: nss*
      state: latest

  - name: Run the installer
    action: command
      {{ ipaserver_base_command }}
      --realm {{ ipaserver_realm }}
      --domain {{ ipaserver_domain }}
      -a {{ ipaserver_admin_password }}
      -p {{ ipaserver_dir_admin_password }}
      --hostname=vm1-freeipa.test.local
      --ip-address={{ ipaserver_ip_address }}
      {{ '--idstart=%s' % ipaserver_idstart if ipaserver_idstart | default(False) else '' }}
      {{ '--idmax=%s' % ipaserver_idmax if ipaserver_idmax | default(False) else '' }}
      {% if ipaserver_setup_dns %}
        --setup-dns
        {% if ipaserver_dns_forwarder | default(False) %}
          {% for forwarder in ipaserver_dns_forwarder %}
            --forwarder={{ forwarder }}
          {% endfor %}
        {% else %}
          --no-forwarders
        {% endif %}
      {% endif %}
      {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(True) else '' }}
      {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }}
      {{ '' if ipaserver_hbac_allow | default(True) else '--no_hbac_allow' }}
      {{ '' if ipaserver_setup_ntp | default(True) else '--no-ntp' }}
      {{ '' if ipaserver_configure_ssh | default(True) else '--no-ssh' }}
      {{ '' if ipaserver_configure_sshd | default(True) else '--no-sshd' }}
      {{ '' if ipaserver_ui_redirect | default(True) else '--no-ui-redirect' }}
      creates=/etc/ipa/default.conf

  - name: add 2 users to freeipa domen
    ipa_user:
      name: "{{ item }}"
      givenname: "{{ item }}"
      sn: "{{ item }}"
      state: present
      ipa_host: vm1-freeipa.test.local
      ipa_user: admin
      ipa_pass: "{{ ipaserver_admin_password }}"

    with_items:
      - user1
      - user2
