---
- name: add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install python and etc
  become: yes
  yum:
    name: 
    - python3
    - python-docker-py
    state: latest

- name: install docker engine
  package:
    name: docker-ce
    state: latest

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes
